title: Eric
description: Personal site
baseurl: "" # for user/organization sites
url: "https://ericgbhk.github.io/"

# ⚠️ DO NOT include this:
# theme: ""

# Optional: include directories if needed
include:
  - _pages
  - _data
  - assets
